channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - graphviz=2.38.0
  - python=3.6.2
  - snakemake=4.0.0
  - pyyaml=3.12
  - pandas=0.22.0
  - simplejson=3.8.1
  - bioservices=1.5.2
  - requests=2.18.4
  - termcolor=1.1.0
  - figlet=0.7.5
  - xlsxwriter=1.0.5