channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - graphviz=2.38.0
  - python=3.6.2
  - snakemake=4.0.0
  - pyyaml=3.12
  - pandas=0.22.0
  - simplejson=3.8.1
  - bioservices=1.5.2
  - matplotlib=2.1.1
  - requests=2.18.4
